language: go

go:
  - "1.11"
  - "stable"

before_install:
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls

install:
  - sudo chown -R $(whoami) /usr/local/bin
  - curl -f https://up.apex.sh/install | sh
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.51_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - go test ./... -v -race -covermode=atomic -coverprofile=coverage.out && cd examples && go test -v -race ./... && cd ..

deploy:
  provider: script
  script: cd docs && hugo && up
  skip_cleanup: true

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - ./bin/up url

env:
  - GO111MODULE=on
