version: 2.1

defaults: &defaults
  working_directory: /tmp/persist_to_workspace

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:

  test:
    <<: *defaults
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout
      - run:
          name: run tests tools
          command: make test test-examples
      - persist_to_workspace:
          root: /tmp/persist_to_workspace
          paths:
            - .

  upload-coverage:
    <<: *defaults
    docker:
      - image: circleci/golang:1.14
    steps:
      - attach_workspace:
         at: /tmp/persist_to_workspace
      - run:
          name: install tools
          command: |
            go get -u -v github.com/axw/gocov/gocov
            go get -u -v github.com/mattn/goveralls
      - run:
          name: generate coverage report
          command: |
            goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN

  deploy-docs:
    <<: *defaults
    docker:
      - image: musitude/go-build:latest
    steps:
      - attach_workspace:
          at: /tmp/persist_to_workspace
      - run:
          name: build docs
          command: cd docs && hugo && cd ..
      - aws-s3/sync:
          from: docs/public/
          overwrite: true
          to: $S3_BUCKET
      - run:
          name: invalidate cloudfront cache
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2

  pipeline:
    jobs:
      - test
      - upload-coverage:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
          requires:
            - test
      - deploy-docs:
          requires:
            - upload-coverage
